site_name: SQLGuide
site_url: https://www.sqlguide.org
theme:
  name: material
  font:
    text: Rubik
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
repo_url: https://github.com/beekeeper-studio/sqlguide.org
repo_name: sqlguide.org
plugins:
  - search
  - tags
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - nl2br
nav:
  - Getting Started: getting-started/index.md
  - Cheat Sheet: cheatsheet/index.md
  - Basic Syntax:
    - basic-syntax/create.md
    - basic-syntax/select.md
    - basic-syntax/insert.md
  - Advanced Syntax: advanced-syntax/index.md
  - Tools: tools/index.md